language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.10"

before_install:
  - cpanm Test::Code::TidyAll
  - cpanm Perl::Critic
  - cpanm Test::Perl::Critic
  - cpanm Perl::Tidy

os: 
  - linux

env:
  - TEST_AUTHOR=1